# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_pipe/mem_pipe.xci
# IP: The module: 'mem_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_pipe/mem_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_pipe'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_pipe/mem_pipe.xci
# IP: The module: 'mem_pipe' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_pipe/mem_pipe_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_pipe'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
