# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_background/mem_background.xci
# IP: The module: 'mem_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_background/mem_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_background'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_background/mem_background.xci
# IP: The module: 'mem_background' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86182/Desktop/vivado workshop/project/project.srcs/sources_1/ip/mem_background/mem_background_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem_background'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
